version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@9.4.0
  aws-cli: circleci/aws-cli@5.2.0

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build_and_push_image:
          auth:
            - aws-cli/setup:
                role_arn: arn:aws:iam::${AWS_ECR_REGISTRY_ID}
          context: aws-env
          create_repo: true
          dockerfile: Dockerfile
          path: ../docker/web/
          repo: circleci-ecr-app-demo
          tag: "$CIRCLE_SHA1"