version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@9.4.0

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build_and_push_image:
          context: aws-dev
          create-repo: true
          dockerfile: Dockerfile
          path: ../docker/web/
          repo: circleci-ecr-app-demo
          tag: "$CIRCLE_SHA1"