version: 2.1

orbs:
  aws-cli: circleci/aws-cli@5.2.0
  aws-ecr: circleci/aws-ecr@9.4.0

jobs:
  build:
    docker:
      - image: cimg/base:stable
    working_directory: ~/project
    steps:
      - checkout
      - setup_remote_docker
      - run:
          # working_directory: work
          name: Setup remote directory
          command: |
            pwd
            ls -la
            mkdir ~/project/work
            pwd
            ls -la
            cp -R Infrastructure ~/project/work/
            cp -R Htdocs ~/project/work/
            pwd
            ls -la
            ls -la ~/project/work
workflows:
  build_and_push_image:
    jobs:
      - build
      # - aws-ecr/build_and_push_image:
      #     auth:
      #       - aws-cli/setup:
      #           role_arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/circleci-oidc-example-role
      #     context: aws-dev
      #     create_repo: true
      #     dockerfile: Dockerfile
      #     path: ./docker/web/
      #     repo: circleci-ecr-app-demo
      #     tag: "$CIRCLE_SHA1"