version: 2.1
jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World"
  ls-test:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
        name: "ls-test"
        command: "ls -al"

workflows:
  say-hello-workflow: 
    jobs:
      - say-hello
      - ls-test