version: 2.1

orbs:
  aws-cli: circleci/aws-cli@5.2.0
  aws-ecr: circleci/aws-ecr@9.4.0

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build_and_push_image:
          auth:
            - aws-cli/setup:
                role_arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/circleci-oidc-example-role
          context: aws-dev
          dockerfile: Dockerfile
          path: ../docker/web/
          repo: circleci-ecr-app-demo
          tag: "$CIRCLE_SHA1"